import { Geist, Geist_Mono, Varela_Round, Quicksand } from "next/font/google";
import "./globals.css";

import "swiper/css"
import "swiper/css/navigation"
import "swiper/css/pagination"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Add Varela Round
const varelaRound = Varela_Round({
  variable: "--font-varela-round",
  subsets: ["latin"],
  weight: ["400"],
});

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // add all weights you need
});

export const metadata = {
  title: "Aktionable-AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${varelaRound.variable} ${quicksand.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
